tap "danielgatis/imgcat"
tap "homebrew/bundle"
tap "homebrew/cask-versions"
tap "homebrew/services"
# Library and utilities for processing GIFs
brew "giflib"
# Library for manipulating PNG images
brew "libpng"
# Automatic configure script builder
brew "autoconf"
# GNU File, Shell, and Text utilities
brew "coreutils"
# Improved shell history for zsh, bash, fish and nushell
brew "atuin"
# Core application library for C
brew "glib"
# Cross-platform make
brew "cmake"
# Get a file from an HTTP, HTTPS or FTP server
brew "curl"
# OpenType text shaping engine
brew "harfbuzz"
# Framework for layout and rendering of i18n text
brew "pango"
# Play, record, convert, and stream audio and video
brew "ffmpeg"
# Command-line fuzzy finder written in Go
brew "fzf"
# GitHub command-line tool
brew "gh"
# Distributed revision control system
brew "git"
# Quickly rewrite git repository history
brew "git-filter-repo"
# GNU Pretty Good Privacy (PGP) package
brew "gnupg"
# Configurable static site generator
brew "hugo"
# Image manipulation library
brew "jpeg"
# Lightweight and flexible command-line JSON processor
brew "jq"
# C library of Git core methods that is re-entrant and linkable
brew "libgit2"
# Library to render SVG files using Cairo
brew "librsvg"
# Access large language models from the command-line
brew "llm"
# Utility for directing compilation
brew "make"
# Polyglot runtime manager (asdf rust clone)
brew "mise"
# NCurses Disk Usage
brew "ncdu"
# Port scanning utility for large networks
brew "nmap"
# Platform built on V8 to build network applications
brew "node"
# Manage multiple Node.js versions
brew "nvm"
# Create, run, and share large language models (LLMs)
brew "ollama"
# Development kit for the Java programming language
brew "openjdk"
# Package compiler and linker metadata toolkit
brew "pkgconf"
# Pack repository contents into a single AI-friendly file
brew "repomix"
# Easiest, most secure way to use WireGuard and 2FA
brew "tailscale"
# Extremely fast Python package installer and resolver, written in Rust
brew "uv"
# Internet file retriever
brew "wget"
# Yet Another Dotfiles Manager
brew "yadm"
# JavaScript package manager
brew "yarn"
# UNIX shell (command interpreter)
brew "zsh"
# Fish-like fast/unobtrusive autosuggestions for zsh
brew "zsh-autosuggestions"
# Fish shell like syntax highlighting for zsh
brew "zsh-syntax-highlighting"
# Display images and gifs in your terminal
brew "danielgatis/imgcat/imgcat"
# Password manager that keeps all passwords secure behind one password
cask "1password"
# Chromium based browser
cask "arc"
# Universal chat app powered by Matrix
cask "beeper"
# Utility that prevents the system from going to sleep
cask "caffeine"
# Write, edit, and chat about your code with AI
cask "cursor"
# Browser for SQLite databases
cask "db-browser-for-sqlite"
# Voice and text chat software
cask "discord"
# Disk usage utility
cask "disk-inventory-x"
# Client for the Dropbox cloud storage service
cask "dropbox"
# Screen colour temperature controller
cask "flux"
# Terminal emulator that uses platform-native UI and GPU acceleration
cask "ghostty"
# Desktop client for GitHub repositories
cask "github"
# Set of tools to manage resources and applications hosted on Google Cloud
cask "google-cloud-sdk"
# Companion app for Home Assistant home automation software
cask "home-assistant"
# Terminal emulator as alternative to Apple's Terminal app
cask "iterm2"
# Noise cancelling application
cask "krisp"
# Discover, download, and run local LLMs
cask "lm-studio"
# Software for Logitech devices
cask "logi-options+"
# Support for Logitech G gear
cask "logitech-g-hub"
# Self-hosted controller built using the Flutter framework
cask "lunasea"
# Provides updates to various Microsoft products
cask "microsoft-auto-update"
# Meet, chat, call, and collaborate in just one place
cask "microsoft-teams"
# Minimal installer for conda
cask "miniconda"
# Free and open-source RSS reader
cask "netnewswire"
# Reverse proxy, secure introspectable tunnels to localhost
cask "ngrok"
# App to write, plan, collaborate, and get organised
cask "notion"
# Knowledge base that works on top of a local folder of plain text Markdown files
cask "obsidian"
# Programmable solid 3D CAD modeller
cask "openscad"
# G-code generator for 3D printers
cask "orcaslicer"
# Home media player
cask "plex"
# Music player focusing on visuals
cask "plexamp"
# Remote pair programming
cask "pop"
# Collaboration platform for API development
cask "postman"
# Tool to reverse the direction of scrolling
cask "scroll-reverser"
# Tool to manage the size and position of windows
cask "shiftit"
# Team communication and collaboration software
cask "slack"
# Controller for Gen 1 Sonos products
cask "sonos-s1-controller"
# Music streaming service
cask "spotify"
# Window manager
cask "tiles"
# Open-source code editor
cask "visual-studio-code"
# Native desktop client for WhatsApp
cask "whatsapp"
# Multiplayer code editor
cask "zed"
# Gecko based web browser
cask "zen-browser"
# Video communication and virtual meeting platform
cask "zoom"
cask "chatgpt"
cask "granola"
cask "claude"
cask "airtable"
cask "nextdns"
cask "granola"

mas "Drafts", id: 1435957248
mas "Windows App", id: 1295203466
mas "TestFlight", id: 899247664
mas "Xcode", id: 497799835


vscode "github.copilot"
vscode "github.copilot-chat"
vscode "mechatroner.rainbow-csv"
vscode "ms-python.debugpy"
vscode "ms-python.python"
vscode "ms-python.vscode-pylance"
vscode "ms-vscode-remote.remote-containers"
